global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres:9187' ]

  - job_name: 'clickhouse'
    static_configs:
      - targets: [ 'clickhouse:9363' ]

  - job_name: 'redis'
    static_configs:
      - targets: [ 'redis:9121' ]

  - job_name: 'airflow'
    metrics_path: '/admin/metrics'
    static_configs:
      - targets: [ 'airflow:8080' ]
